tse new feature correcction
falguniislam/RUBY-PROJECT-Advanced-Building-Blocks---Bubble-Sort pull request #4
Opened 2019-10-18 12:23 UTC by falguniislam

## Project 1: Bubble Sort
Sorting algorithms are some of the earliest that you typically get exposed to in Computer Science. It may not be immediately obvious how important they are, but it shouldn’t be hard to think of some examples where your computer needs to sort some massive datasets during everyday operations.

2019-10-18 17:00 UTC, uche-inyama requested changes
## Hi Falguniislam, :wave: 

After going through your code, I made the following observation:

- [x] Your first function in your new bubblesort.rb file, does not sort the array. I also observed you did not loop with ' _i ' index you inserted into "pipe". Kindly fix that. :slightly_smiling_face: 

- [x] Also, work on the linter errors.

However, the bubblesort.rb file you deleted, the function sorted the array, properly.

``` 
def bubble_sort(arr)
  arr.each do
    i = 0
    swap = 0
    while i < arr.length - 1
      if arr[i] > arr[i + 1]
        temp = arr[i]
        arr[i] = arr[i + 1]
        arr[i + 1] = temp
      end
      i += 1
      swap += 1 
    end
    break if swap.zero?
  end
end

```

After implementing this change submit another form for a code review.

#### ``` Have a nice day ``` :slightly_smiling_face: 

@ Uchechukwu Henry Inyama

2019-10-22 16:45 UTC, maelfosso requested changes
Hello @falguniislam @davidauza-engineer 

Nice improvements :smile: 
To make the project approved, you need to just change some lines. Please, read the comments below and **correct the sticklers errors**

Also, **Follow the Git Flow** otherwise the project won't be approved.
- Do not work directly in the master branch. Create the development branch and a specific feature-branch (give it a descriptive name) for every feature you implement. When your feature is ready and approved you can merge feature-branch to the development branch and when the release is ready create a pull request from development to master.
- Read more [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/)

Kindly make the changes and submit a new code review request.

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com)

2019-10-22 16:45 UTC, maelfosso commented on README.md
> +  puts arr.join(' ')
You must return the array not print it

2019-10-22 16:45 UTC, maelfosso commented on README.md
> +  puts array.join(' ')
You must return the array not print it

2019-10-22 16:45 UTC, maelfosso commented on README.md
> +end
Not needed

2019-10-22 17:40 UTC, davidauza-engineer commented on README.md
> +  puts arr.join(' ')
Done :)

2019-10-22 17:40 UTC, davidauza-engineer commented on README.md
> +  puts array.join(' ')
Done :)

2019-10-22 17:40 UTC, davidauza-engineer commented on README.md
> +end
Successfully removed :)

2019-10-22 17:42 UTC, davidauza-engineer reviewed
All suggested changes were done. Thank you so much. Please let us know if everything is OK now :)

2019-10-22 17:57 UTC, davidauza-engineer commented
Accidentally closed, reopening...

2019-10-22 18:07 UTC, maelfosso approved these changes
# You did it :smile:  Congratulations :clap: 
# The project is approved :+1: 

You can merge the project now.
Good luck with the next project

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com)

2019-10-22 18:50 UTC, merged

2019-10-23 03:49 UTC, davidauza-engineer commented
Thanks a lot @maelfosso 👍